---
- name: clickhouse
  src: https://github.com/NamorNinayzuk/ansible-clickhouse.git
  scm: git
  version: 0.0.3
- name: vector-role
  src: https://github.com/NamorNinayzuk/vector-role
  scm: git
  version: 0.0.4
- name: lighthouse-role
  src: https://github.com/NamorNinayzuk//lighthouse-role.git
  scm: git
  version: 0.0.3
...
